name: First GitHub Action Test

on: push  # Jab bhi koi push kare ga, ye run ho ga

jobs:
  test:
    runs-on: ubuntu-latest  # Ye GitHub ka provided runner hai
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "Hello, GitHub Actions is working!"  # Simple test
